server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: HostelBooking
  jpa:
    generate-ddl: true
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgres
    password: postgres
    hikari:
      schema: booking
      connection-init-sql: create schema if not exists booking
      connection-timeout: 10000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
#app:
#  kafka:
#    kafkaMessageRegisterTopic: "register-topic"
#    kafkaMessageNewBookingTopic: "new-booking-topic"
#    kafkaMessageGroupId: "kafka-message-group-id"

