spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgres
    password: postgres
    hikari:
      schema: hotel_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hotel_schema
      connection-timeout: 10000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

#  security:
#    user:
#      name: admin
#      password: admin
#      roles: ADMIN
